Dao idls pda getters
staratlasmeta/factory pull request #111
Opened 2022-10-05 12:31 UTC by Cain310

- Add DAO idls and pda getters

## Changes

## Checklist

- [ ] UAT
- [ ] Passes final QA checks

2022-10-05 19:53 UTC, remjx requested changes

2022-10-05 19:53 UTC, remjx commented on src/dao/constants.ts
> +  LOCKER: new PublicKey('5WmM9c9WE71y78Ah8Bp8vgyoStscM1ZZyaaFqRf8b2Qa'),
Can we create a namespace or some naming scheme to distinguish between ATLAS and POLIS locker variables? One step in this direction would be to nest everything inside an `atlas-locker` folder, but we should make sure there is no confusing overlap when people are importing functions/modules. Perhaps in the `index.ts` export all of these under a `polisLocker` namespace.

2022-10-05 19:53 UTC, remjx commented on src/dao/pda_getters/proxy_rewarder_Pda.ts
> +  return await PublicKey.findProgramAddress(
`await` is redundant if you are returning a promise. (There are other cases of this in the code, but just making a single comment for brevity. You can find them by searching `return await`)
```suggestion
  return PublicKey.findProgramAddress(
```

2022-10-05 19:53 UTC, remjx commented on src/dao/constants.ts
> +export const STAR_ATLAS_ADDRESSES = {
I don't see a need to separate `STAR_ATLAS_ADDRESSES` and `DAO_ADDRESSES`, can we combine them into a single var?

2022-10-05 19:53 UTC, remjx commented on src/dao/pda_getters/locked_voter_Pda.ts
> + * Finds the address of an Escrow.
Is there a follow-up task to add more than just these basic `getters` to factory?

2022-10-05 19:53 UTC, remjx commented on src/dao/pda_getters/seeds.ts
> +export const PROXY_SEED = Buffer.from('Proxy');
Move these to `constants.ts`?

2022-10-05 19:53 UTC, remjx commented on src/dao/types/lockedVoterIdl.ts
> +  version: '0.1.0';
This version does not align with the version in the `polis-dao` repo
```
export type LockedVoterIDL = {
  version: "0.5.6";
  ```
Did you manually set this version number? I think we should keep them in sync.

2022-10-07 13:00 UTC, Cain310 commented on src/dao/pda_getters/seeds.ts
> +export const PROXY_SEED = Buffer.from('Proxy');
ok

2022-10-07 13:01 UTC, Cain310 commented on src/dao/pda_getters/locked_voter_Pda.ts
> + * Finds the address of an Escrow.
I think the follow up to this will be when/if we decide to add the wrappers and/or function calls.

2022-10-11 15:07 UTC, closed without merging