Cu 1kc8162 score typescript interface
staratlasmeta/factory pull request #21
Opened 2021-10-19 20:56 UTC by bzierk

## Changes

## Checklist

- [ ] UAT
- [ ] Passes final QA checks

2021-10-19 20:56 UTC, bravetarget commented
Task linked: [CU-1kc8162 FACTORY - SCORE: Deposit ship to escrow](https://app.clickup.com/t/1kc8162)

2021-11-16 01:08 UTC, turnyay requested changes

2021-11-16 01:08 UTC, turnyay commented on src/util/scoreHelpers.ts
> +  const [associatedTokenAccount] = await getAtaForMint(mint, payer);
payer should be owner here

2021-11-16 01:08 UTC, turnyay commented on src/util/scoreHelpers.ts
> +  const [aTokenAccount] = await getAtaForMint(mint, provider.wallet.publicKey);
move this below the owner check and set the pubkey to owner

2021-11-16 01:08 UTC, turnyay commented on src/util/scoreHelpers.ts
> +    provider.wallet.publicKey,
this should be mintAuthority right?

2021-11-16 01:08 UTC, turnyay commented on src/util/scoreHelpers.ts
> +  associatedTokenAccount: web3.PublicKey,
rename this to just tokenAccount ?

2021-11-16 01:08 UTC, turnyay commented on src/util/scoreHelpers.ts
> +
delete empty lines

2021-11-16 01:08 UTC, turnyay commented on src/util/scoreHelpers.ts
> +  assert(tokenAmount == expectedQuantity);
you can add a message to help debug
something like "On-chain Token amount of <> does not match expected amount <>"

2021-11-16 02:30 UTC, turnyay approved these changes

2021-11-16 02:31 UTC, merged