fix(gmp): Bug where onEvent could be null
staratlasmeta/factory pull request #95
Opened 2022-08-16 02:01 UTC by staratlasjim

## Changes

- Working through a bug where the GmEventService doesn't correctly handle the `onEvent` callback handler being null.
- If the health check service determines that the GmEventService needs to be restarted, the `onEvent` handler would be set to null.
- GmOrderBookService.ts: This fixes both the condition that inadvertently set the GmEventService::onEvent to null (line 116).
- Added logic to handle not having an `onEvent` handler in the GmEventService.

- some formatting changes due to prettier/eslint configs in my ide.

## Checklist

- [ ] UAT
- [ ] Passes final QA checks

2022-08-16 02:01 UTC, bravetarget commented
Task linked: [CU-2nvdmn8 [Bug] Orders not loading in category orders view](https://app.clickup.com/t/2nvdmn8)

2022-08-16 15:21 UTC, MikeLuDev requested changes
Could you revert the changes to quotation marks?

2022-08-16 15:29 UTC, MikeLuDev commented on src/marketplace/services/GmEventService.ts
> +    // had a connection from a client and hasn't created rooms yet
```suggestion
```

I'd leave this out - this is a public repository and the general audience doesn't have context on `StarComm` *yet*

2022-08-16 17:22 UTC, staratlasjim commented on src/marketplace/services/GmEventService.ts
> +    // had a connection from a client and hasn't created rooms yet
@mikeludev - removed those comments.  Also now that Prettier is in, I left the single quotes.

2022-08-24 19:36 UTC, Buzzec commented on src/marketplace/services/GmOrderbookService.ts
Does `onEvent` need to be set to null here so that events are queued while re-initializing?

2022-08-24 19:56 UTC, staratlasjim commented on src/marketplace/services/GmOrderbookService.ts
Great question: @Buzzec.  

Yes, it does, however it is already set to `null`

On line 109, it calls
-  `await this.gmEventService.end();`
- `GmEventService::End()`, line 112 sets `onEvent = null`.

As soon as `end` is called, the handler is null. 

Also, line 116 should remove the major use case where the event queue was the safety net, as `resetEventService` used to call `end` but not re-add the event handler.

2022-08-30 18:29 UTC, MikeLuDev approved these changes

2022-08-30 18:29 UTC, merged